### PR TITLE
Added missing Bearer prefix to Authorization Header in the template-plugin-auth

### PR DESCRIPTION
**Pull request by roblperry**
Intended to address Template code should Authenticate with Bearer Token #143

### CODE REVIEW

**Comment by roblperry** [comment]
BTW, I did create a new project with my branch and observed the Account page working.

**Comment by AnthonyMichaelTDM** [comment]
Oh, thanks for catching this. I don't do frontend dev, so when I updated the backend auth service to use the bearer prefix for RFC-6570 compliance in #88 I must not've though to update the generated frontend to match.

**Review by AnthonyMichaelTDM — APPROVED** [review]
looks good to me

**Comment by Wulf** [comment]
nice catch @roblperry :)

I did a [control+f](https://github.com/Wulf/create-rust-app/commit/7d3fca367f3a9fa78a92acc87706e2b3c65b437b#diff-9d3079bad27ef481440534ad60295ed41eff4f7e257a005f837ac3ff14e246c9L249) to find these, don't know how I missed this one :sweat_smile: 

I think it's time to introduce a changelog -- #145

**Pull request merged**
