### PR TITLE
Use most recent versions of dsync and tsync, fix #70

### LINKED ISSUE #70: Generated cargo.toml has out of date dependencies
As said in the title, the dependencies in the generated cargo.toml file are out of date, I'll soon be making a pull request that updates the dsync and tsync versions (as those are the most critical), and I can make another one that updates the rest of the dependencies too if that'd be helpful

### PR DESCRIPTION
**Pull request by AnthonyMichaelTDM**
fixes #70

### CODE REVIEW

**Comment by AnthonyMichaelTDM** [comment]
seems to cut testing time in half

**Comment by Wulf** [comment]
let's use a caret version like `"^1"` and call cargo update on the package `cargo update -p tsync`. The problem with specifying a version is that it becomes the maintainer's job to make sure it's up-to-date which becomes difficult and will require new releases everytime dsync/tsync get updated.

**Comment by AnthonyMichaelTDM** [comment]
Oh yeah, good idea

**Comment by Wulf** [comment]
Going to close this change is already in `main` somehow :sweat_smile:

**Comment by AnthonyMichaelTDM** [comment]
👍

**Pull request closed without merging**
