### PR TITLE
Remove useless argonautica dependency from service_poem.rs fix #80

### LINKED ISSUE #80: Compile Error: Use of undeclared crate or module `argonautica`
I followed the quick start to create a new app.

When I run `cargo fullstack` or `cargo build`, I receive the following error:

```
   Compiling create-rust-app v8.1.1
error[E0433]: failed to resolve: use of undeclared crate or module `argonautica`
 --> /Users/rohit/.cargo/registry/src/github.com-1ecc6299db9ec823/create-rust-app-8.1.1/src/dev/endpoints/service_poem.rs:1:5
  |
1 | use argonautica::config::Version::_0x10;
  |     ^^^^^^^^^^^ use of undeclared crate or module `argonautica`
```

Originates here:

https://github.com/Wulf/create-rust-app/blob/50cd54b14d50ac1b733fd653723978518344a1ec/create-rust-app/src/dev/endpoints/service_poem.rs#L1

### PR DESCRIPTION
**Pull request by AnthonyMichaelTDM**
Fixes #80 

 The argonautica dependency didn't seem to be used anywhere in the file so I just removed it.

### CODE REVIEW

**Comment by AnthonyMichaelTDM** [comment]
there were none

**Comment by AnthonyMichaelTDM** [comment]
@Wulf How do I request a review in this repository?

**Comment by Wulf** [comment]
Thanks for investigating and fixing this @AnthonyMichaelTDM, I'll try to cut a release for this today. Regarding reviews; I try to hop on when I have time to go through the pull requests and issues. Over the past month, I've been fairly busy and also fell sick but I'm back now 🚀. Lastly, I've invited you to become a collaborator :)

**Comment by AnthonyMichaelTDM** [comment]
Awesome! Thank you

**Pull request merged**
