### PR TITLE
9.1.0

### PR DESCRIPTION
**Pull request by Wulf**
* Fixes compilation issues :rocket: (#140)
* View dev-hosted app outside the network (for example, now you can view the local app on your phone!)
* `qsync` updates
* Updated service boilerplate generation (#102)
* Other minor issues including #168

### CODE REVIEW

**Comment by Wulf** [comment]
:thinking: the CI isn't invoking dsync to generate DB code I think. Don't have time to look at it now -- let's fix this up later; I'm glad it's compiling :)

**Comment by AnthonyMichaelTDM** [comment]
> thinking the CI isn't invoking dsync to generate DB code I think. Don't have time to look at it now -- let's fix this up later; I'm glad it's compiling :)

Oh yeah, good catch

but there's an issue, the generated project doesn't include the diesel schema (that's generated by diesel), in order to do this properly every CI run would need a postgress container attached to it (easy to do) and diesel installed (easy, but will take a really long time unless I figure something out with caches or something)

**Comment by AnthonyMichaelTDM** [comment]
https://docs.rs/diesel_migrations/latest/diesel_migrations/macro.embed_migrations.html could help us? idk though

**Comment by AnthonyMichaelTDM** [comment]
oh actually, maybe we can create a schema.rs in the CI, thne run dsync

any failures from a back schema then should only happen at runtime

**Pull request merged**
